/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cuahanglinhkien_java.views;

import com.mycompany.cuahanglinhkien_java.controllers.ProductController;
import com.mycompany.cuahanglinhkien_java.controllers.InventoryController;
import com.mycompany.cuahanglinhkien_java.models.Inventory;
import com.mycompany.cuahanglinhkien_java.models.Product;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DLCT
 */
public class frmInventory extends javax.swing.JFrame {

    InventoryController controller = new InventoryController();
    ProductController controllerPro = new ProductController();
    String[] columnNames = {"Mã", "Ngày nhập", "Số lô", "Số lượng nhập", "Tồn kho", "Giá nhập", "Tổng giá trị"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    int productId;
    
    /**
     * Creates new form frmCategory
     */
    public frmInventory(int productId) {
        initComponents();
        tbInventory.setModel(model);
        this.productId = productId;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInventory = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtBatchNumber = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        spQuantity = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        spImportPrice = new javax.swing.JSpinner();
        jPanel15 = new javax.swing.JPanel();
        btnImport = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 640));
        setSize(new java.awt.Dimension(500, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ NHẬP HÀNG");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        tbInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ngày nhập", "Số lô", "Số lượng nhập", "Tồn kho", "Giá nhập", "Tổng giá trị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInventoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInventory);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 672;
        gridBagConstraints.ipady = 430;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thông tin sản phẩm");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.GridLayout(6, 0, 0, 10));

        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        jLabel3.setText("Mã sản phẩm");
        jPanel5.add(jLabel3);

        txtProductID.setFocusable(false);
        jPanel5.add(txtProductID);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel4.setText("Tên sản phẩm");
        jPanel6.add(jLabel4);

        txtProductName.setFocusable(false);
        jPanel6.add(txtProductName);

        jPanel4.add(jPanel6);

        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel6.setText("Số lô");
        jPanel8.add(jLabel6);
        jPanel8.add(txtBatchNumber);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new java.awt.GridLayout(2, 0));

        jLabel7.setText("Số lượng nhập");
        jPanel9.add(jLabel7);
        jPanel9.add(spQuantity);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(2, 0));

        jLabel8.setText("Giá nhập");
        jPanel10.add(jLabel8);
        jPanel10.add(spImportPrice);

        jPanel4.add(jPanel10);

        jPanel15.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        btnImport.setText("Nhập hàng");
        btnImport.setPreferredSize(new java.awt.Dimension(100, 43));
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel15.add(btnImport);

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel15.add(btnExit);

        jPanel4.add(jPanel15);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInventoryMouseClicked

    }//GEN-LAST:event_tbInventoryMouseClicked

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed

        String batchNumber = txtBatchNumber.getText().trim();
        int quantity = Integer.parseInt(spQuantity.getValue().toString());
        float importPrice = Float.parseFloat(spImportPrice.getValue().toString());

        //Inventory newInventory = new Inventory(productId, batchNumber, quantity,importPrice);
        if (!batchNumber.isBlank() && quantity > 0 && importPrice > 0) {
            Inventory newInventory = new Inventory(productId, batchNumber, quantity, importPrice);
            controller.ImportProduct(newInventory);
        }
        loadTable();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //this.dispose();
        frmProduct productForm = new frmProduct();
        productForm.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed
    
    private void loadTable() {
        InventoryController controller = new InventoryController();
        Product pro = controllerPro.getProductById(productId);
        txtProductID.setText(productId+"");
        txtProductName.setText(pro.getName());
        List<Inventory> listInventory = controller.getProductById(productId);
       
        DefaultTableModel model = (DefaultTableModel) tbInventory.getModel();
        model.setRowCount(0);

        listInventory.forEach(inventory -> {
            model.addRow(new Object[]{
                inventory.getId(),
                inventory.getImportDate(), 
                inventory.getBatchNumber(), 
                inventory.getQuantityImported(),
                inventory.getStockQuantity(),
                inventory.getImportPirce(), 
                inventory.getTotal() 
            });
        });

    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnImport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spImportPrice;
    private javax.swing.JSpinner spQuantity;
    private javax.swing.JTable tbInventory;
    private javax.swing.JTextField txtBatchNumber;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables

    

}
