/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cuahanglinhkien_java.views;

import com.mycompany.cuahanglinhkien_java.controllers.CustomerController;
import com.mycompany.cuahanglinhkien_java.controllers.EmployeeController;
import com.mycompany.cuahanglinhkien_java.controllers.OrderController;
import com.mycompany.cuahanglinhkien_java.models.Customer;
import com.mycompany.cuahanglinhkien_java.models.Employee;
import com.mycompany.cuahanglinhkien_java.models.InvoiceModel;
import com.mycompany.cuahanglinhkien_java.models.Order;
import java.io.FileOutputStream;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import com.mycompany.cuahanglinhkien_java.models.InvoiceItem;
import java.util.Date;
import javax.swing.JOptionPane;
import static share.utils.StringFormat.formatCurrencyVND;

/**
 *
 * @author YEN VY
 */
public class frmOrder extends javax.swing.JFrame {
    EmployeeController employeecontroller=new EmployeeController();
    CustomerController customerController=new CustomerController();
    OrderController ordercontroller=new OrderController();
    String[] columnNames = {"Mã đơn hàng","Số điện thoại", "Ngày mua", "Trạng thái", "Tổng tiền "};
    DefaultTableModel model = new DefaultTableModel(columnNames,0);
    int selected =-1;

    /**
     * Creates new form frmOrder
     */
    public frmOrder() {
        initComponents();
        tbOrder.setModel(model);
        addEvent();
        loadData();
        clearInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 126, 242));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(7, 0, 0, 10));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel2.setText("Mã đơn hàng");
        jPanel5.add(jLabel2);

        txtID.setFocusable(false);
        jPanel5.add(txtID);

        jLabel3.setText("Số điện thoại");
        jPanel5.add(jLabel3);
        jPanel5.add(txtPhoneNumber);

        jPanel3.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel4.setText("Tên khách hàng");
        jPanel7.add(jLabel4);

        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtName.setFocusable(false);
        jPanel7.add(txtName);

        jPanel3.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jLabel6.setText("Địa chỉ");
        jPanel6.add(jLabel6);

        txtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAddress.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAddress.setFocusable(false);
        jPanel6.add(txtAddress);

        jPanel3.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(2, 0));

        jLabel5.setText("Trạng thái");
        jPanel8.add(jLabel5);

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Hoàn thành", "Hủy" }));
        cbStatus.setFocusable(false);
        jPanel8.add(cbStatus);

        jPanel3.add(jPanel8);

        jPanel10.setBackground(new java.awt.Color(204, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(2, 3));

        jPanel14.setBackground(new java.awt.Color(204, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Tổng tiền");
        jPanel14.add(jLabel7, java.awt.BorderLayout.LINE_START);

        txtTotal.setFocusable(false);
        jPanel14.add(txtTotal, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel14);

        jPanel3.add(jPanel10);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(2, 0));

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel15);
        jPanel9.add(txtSearch);

        jPanel3.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(204, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(2, 0));

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        btnSearch.setText("Tìm kiếm");
        jPanel12.add(btnSearch);

        btnPrint.setText("Xuất hóa đơn");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel12.add(btnPrint);

        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 255, 255));
        jPanel13.setLayout(new java.awt.GridLayout(1, 3, 5, 0));

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel13.add(btnAdd);

        btnView.setText("Xem");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel13.add(btnView);

        btnCancel.setText("Hủy");
        jPanel13.add(btnCancel);

        jPanel11.add(jPanel13);

        jPanel3.add(jPanel11);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbOrder);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String phoneNumber=txtPhoneNumber.getText();
        String name=txtName.getText();
        String address=txtAddress.getText();
        if(!phoneNumber.isBlank()&& !name.isBlank()&& !address.isBlank()){
            Customer customer = customerController.getCustomerByPhoneNumber(phoneNumber);
            if(customer==null){
                customerController.addCustomer(new Customer(phoneNumber, name, address));
            }
            ordercontroller.addOrder(new Order(phoneNumber));
            loadData();
            clearInput();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if (selected != -1) {
            InvoiceModel invoice = ordercontroller.getInvoiceData(selected);
            try {
                exportInvoiceToPDF(invoice);
                JOptionPane.showMessageDialog(null, "Xuất hóa đơn thành công!");
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Lỗi khi xuất hóa đơn!");
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if (selected != -1) {
            frmOrderDetails frmDetail = new frmOrderDetails(selected, this);
            frmDetail.setLocationRelativeTo(null);
            frmDetail.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frmDetail.setVisible(true);
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmHome frmHome = new frmHome();
        frmHome.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmHome.setVisible(true);        
    }//GEN-LAST:event_formWindowClosing

    protected void loadData() {
        List<Order> orders = ordercontroller.getAllOrder();

        model.setRowCount(0);
        orders.forEach(order -> {
            model.addRow(new Object[]{order.getId(), order.getPhoneNumber(), order.getPurchaseDate(), order.getStatus(), order.getTotalAmount()});
        });
    }
    private void addEvent() {
        tbOrder.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tbOrder.getSelectedRow();
                if (selectedRow != -1) {
                    selected = Integer.parseInt(tbOrder.getValueAt(selectedRow, 0).toString()) ;
                    Order order= ordercontroller.getOrder(selected);
                    txtID.setText(selected+"");
                    txtPhoneNumber.setText(order.getPhoneNumber());
                    cbStatus.setSelectedItem(order.getStatus());
                }
            }
        });
        txtPhoneNumber.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String phoneNumber = txtPhoneNumber.getText();
                Customer customer = customerController.getCustomerByPhoneNumber(phoneNumber);
                if (customer != null) {
                    txtName.setText(customer.getName());
                    txtAddress.setText(customer.getAddress());
                    txtName.setEnabled(false);
                    txtAddress.setEnabled(false);
                } else {
                    txtName.setText("");
                    txtAddress.setText("");
                    txtName.setEnabled(true);
                    txtAddress.setEnabled(true);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String phoneNumber = txtPhoneNumber.getText();
                Customer customer = customerController.getCustomerByPhoneNumber(phoneNumber);
                if (customer != null) {
                    txtName.setText(customer.getName());
                    txtAddress.setText(customer.getAddress());
                    txtName.setEnabled(false);
                    txtAddress.setEnabled(false);
                } else {
                    txtName.setText("");
                    txtAddress.setText("");
                    txtName.setEnabled(true);
                    txtAddress.setEnabled(true);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Không cần xử lý, vì không thay đổi thuộc tính hiển thị (như font, style).
            }
        });
    }
    
    private void clearInput() {
        txtPhoneNumber.setText("");
        txtName.setText("");
        txtAddress.setText("");
        txtTotal.setText("");
    }
    
    public static void exportInvoiceToPDF(InvoiceModel invoice) throws Exception {
        String path = System.getProperty("user.dir");
        String baseFontPath = path + "\\src\\main\\java\\share\\arialuni.ttf";
        
        Document document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream("C:/CuaHangLinhKien/" + invoice.getCustomerName() 
                + invoice.getPhone() + ".pdf"));
        document.open();

        String fontPath = baseFontPath;
        BaseFont baseFont = BaseFont.createFont(fontPath, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
        Font font = new Font(baseFont, 12);
        
        document.add(new Paragraph("INVOICE", font));
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Customer name: " + invoice.getCustomerName(), font));
        document.add(new Paragraph("Phone number: " + invoice.getPhone(), font));
        document.add(new Paragraph("Address: " + invoice.getAddress(), font));
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Employee name: " + invoice.getEmployeeName(), font));
        document.add(new Paragraph(" "));
        
        document.add(new Paragraph("Product list:", font));
        List<InvoiceItem> items = invoice.getItems();
        for (int i = 1; i <= items.size(); i++){
            InvoiceItem item = items.get(i-1);
            document.add(new Paragraph(i + ". " + item.getProductName() + " - Quantity: " 
                    + item.getQuantity() + " - Price: " + formatCurrencyVND(item.getPrice()) + "VND", font));
        }
        document.add(new Paragraph(" "));

        document.add(new Paragraph("Total: " + formatCurrencyVND(invoice.getTotalPrice()) + "VND", font));

        document.close();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOrder().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
